name: module3_task1
on:
  push:
    branches: [ main ]
  pull_request: [ main ]
jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install
        run: |
          cd module3_task1
          ./setup.sh
      - name: Build
        run: |
          cd module3_task1
          make build
